sudo: required
dist: trusty
group: edge

services:
- docker
env:
  global:
  - NG_ENVIRONMENT=Stage
  - LANDMARK=http://informationcart.eastus2.cloudapp.azure.com:80/api/
  - MAPSAPI=http://informationcart.eastus2.cloudapp.azure.com:82/api/
  - secure: jm2AKgkxzwOM05AJPN8NfTNZ0zcOf80brh6/mgOj0AhfptGVlGBE9IbcB2pjv+vZbHwDk9mtmt0M8ZRgfXYDBxLmTUAOZPeoalxrH2MWFc8t07lyyBB63FVlQZDqwPogKt1lJXy7t4Zb07RwHKFWV6VMWs8p24MHNC1hK9mVgRO/3S6M95YUqJvSs6/4jYoSJuF2hgXU1Kr5WaE43MFl3Fr1A/wbYavMGy+ZVzd+/PiRzxxpBtJ1rN1l2l5pOf8+NouBkgW4IBCfYaZzkBIkmfrJieayDrn1KCw9OC2pPDamIwvJ2lk1HBlCLCJ7SYDwxmtoL6EBEJBisxwLnoqapdob699bDZao282FHL19K6wGpehljt8jYza4xW/ELOt10lYyY/egSQBX8h61+bt2cniDhhQdNFaA0huaOrwN4HkZj88qXMA7mIbyu5TkQMRvazlzEu0tzvGEu/RiVXwIFoYoveHugy3YBkk4BXw3NqIg1kxMh6TdF+SPQPwHZrC8eUQW1QCghF0ImpBU5UwDWMCwZQ6z7kwrmWPrVfv9DlzFfeZAohF8O39opUq7aFOYOvAnZKTp0FjO+ombCZJXx9q2z2VV/tSbPV3SRXF474u+J9CRJyOwfUERzRK8M4ezVwKkEq9H7tHwJUBs/RhhqaGQF0co6O8S6x1IxSRvIRw=
language: node_js
node_js:
- '4'
- '5'
- '6'
- '7'
cache:
  directories:
  - node_modules

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - cd src/CoreDataStore.Web

script:
  - npm run clean
  - npm run build

after_success:
  - cd ../..
  - docker build -f docker/node.dockerfile -t stuartshay/coredatastore:travis$TRAVIS_BUILD_NUMBER-$TRAVIS_NODE_VERSION .
  - docker run -d -p 3000:3000 stuartshay/coredatastore:travis$TRAVIS_BUILD_NUMBER-$TRAVIS_NODE_VERSION
  - docker ps -a
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push stuartshay/coredatastore:travis$TRAVIS_BUILD_NUMBER-$TRAVIS_NODE_VERSION;
    fi
notifications:
  slack: leduong:8FHnajypcfOykiQS6Hn6QBB5