version: '1.0.{build}'


branches:  
  only:
  - core-net-1-0

before_build:
 npm install -g npm3
 npm3 install -g typings
- cmd: DOTNET restore
 
build:
 cd src\CoreDataStore.Web\
- cmd: DOTNET build


test: off 