version: '1.0.{build}'
image: Visual Studio 2017

init:
- dotnet --info

environment:  
  DOCKER_USER:
    secure: tuvYPlVYg0PZLnBt+UZnxw==
  DOCKER_PASS:
    secure: UTjxeq5UB9NSf1QUF3rUvw==

install:  
  - docker version

build_script:  
  - docker build -f docker/nanoserver.dockerfile -t stuartshay/coredatastore:nanoserver .

deploy_script:  
  - docker login -u="stuartshay" -p="Yankees2015"
  - docker push stuartshay/coredatastore:nanoserver




#build_script:
#- cmd: dotnet publish .\src\CoreDataStore.Web


#test_script:
#- ps: foreach ($d in dir .\test |? {$_.PSIsContainer -eq $True}){ &"dotnet" "test" $d.FullName }

#artifacts:
#  path: .\src\CoreDataStore.Web\bin\Debug\netcoreapp1.0\publish
