version: '1.0.{build}'


branches:  
  only:
  - core-net-1-0

before_build:
 npm install -g npm3
 npm3 install -g typings
 
build:
 DOTNET restore
 cd src\CoreDataStore.Web\
 DOTNET build


test: off 