version: '1.0.{build}'
image: Visual Studio 2017

init:
- dotnet --info
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
  nodejs_version: "6"
  DOCKER_USER:
    secure: 3KiV+zYEcvwJrrLP+jZRjhY7+3s/SWUNdM8mRH4d8Kw=
  DOCKER_PASS:
    secure: TctN/Vl+j8edPvq1b86mDG4D8CS6DSTWMNyq1TXbB54=

cache:
  - src/CoreDataStore.Web/node_modules
  - '%APPDATA%\npm-cache'             # npm cache
  - '%USERPROFILE%\.nuget\packages    # package cache

install:
  - dir
  - dotnet restore
  - dotnet publish src/CoreDataStore.Web/CoreDataStore.Web.csproj -c Release -f netcoreapp1.1 -r win10-x64
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm@3
  - cd src/CoreDataStore.Web
  - npm i
  - npm run clean
  - npm run build
  - cd ../..

test_script:
  - node --version
  - npm --version
  - docker version

build_script:  
  - ps: docker build -f docker/runtime-nanoserver.dockerfile -t "stuartshay/coredatastore:nanoserver-$env:APPVEYOR_BUILD_NUMBER" .

deploy_script:  
 - ps: docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"
 - ps: docker push "stuartshay/coredatastore:nanoserver-$env:APPVEYOR_BUILD_NUMBER"

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))



#test_script:
#- ps: foreach ($d in dir .\test |? {$_.PSIsContainer -eq $True}){ &"dotnet" "test" $d.FullName }

#artifacts:
#  path: .\src\CoreDataStore.Web\bin\Debug\netcoreapp1.0\publish
