version: '2'

services:

  web:
    build:
      context: .
      dockerfile: docker/aspnetcore.dockerfile
    ports:
     - "5000:5000"
    networks:
      - aspnetcoreapp-network

  postgres:
    build:
      context: .
      dockerfile: docker/postgres.dockerfile
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - aspnetcoreapp-network

  nginx:
    build:
      context: .
      dockerfile: docker/nginx.dockerfile
    ports:
     - "80:80"
    networks:
      - aspnetcoreapp-network
networks:
  aspnetcoreapp-network:
    driver: bridge
