coredatastore-lb:
  ports:
  - 80:5000
  labels:
    io.rancher.loadbalancer.target.coredatastore-web: /
    # Host MUST have the label `io.rancher.host.type=manager`
    io.rancher.scheduler.affinity:host_label: io.rancher.host.type=manager
  tty: true
  image: rancher/load-balancer-service
  links:
  - coredatastore-web:coredatastore-web
  stdin_open: true
coredatastore-web:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    # Host MUST have the label `io.rancher.host.type=worker`
    io.rancher.scheduler.affinity:host_label: io.rancher.host.type=worker
  tty: true
  image: stuartshay/coredatastore:stable
  stdin_open: true
database:
  environment:
    POSTGRES_PASSWORD: password
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    # Host MUST have the label `io.rancher.host.type=worker`
    io.rancher.scheduler.affinity:host_label: io.rancher.host.type=worker
  tty: true
  image: stuartshay/coredatastore-postgres:stable
  stdin_open: true
