version: '2'

services:

  nginx:
    container_name: 'coredatastore_nginx'
    image: "stuartshay/coredatastore-nginx:latest"
    depends_on:
     - "web"
    links:
        -  web
    ports:
        - "80:80"


  web:
    container_name: 'coredatastore_web'
    image: "stuartshay/coredatastore:latest"
    volumes:
      - .:/var/www/aspnetcoreapp
    ports:
     - "5000:5000"
    depends_on:
     - "database"
    networks:
      - aspnetcoreapp-network


  database:
    container_name: 'database'
    image: "stuartshay/coredatastore-postgres:stable"
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - aspnetcoreapp-network


networks:
  aspnetcoreapp-network:
    driver: bridge










