version: '2'

services:

  web:
    build:
      context: .
      dockerfile: aspnetcore.dockerfile
    ports:
     - "5000:5000"
    networks:
      - aspnetcoreapp-network

  postgres:
   build:
      dockerfile: postgres.dockerfile
   environment:
      POSTGRES_PASSWORD: password
   ports:
     - "5432:5432"
    networks:
      - aspnetcoreapp-network

networks:
  aspnetcoreapp-network:
    driver: bridge
