version: '2'

services:

  web:
    image: stuartshay/coredatastore:latest
    ports:
     - "5000:5000"
    networks:
      - aspnetcoreapp-network

  database:
      image: stuartshay/coredatastore-postgre:stable
      environment:
      POSTGRES_PASSWORD: password
    networks:
      - aspnetcoreapp-network

networks:
  aspnetcoreapp-network:
    driver: bridge