version: '2'

services:
  db:
    image: postgres
    
    environment:
      - POSTGRES_USER="coredatastore"
      - POSTGRES_PASSWORD="123456"

    networks:
      - app-internal

  web:
    image: stuartshay/coredatastore

    links:
      - db
  
    environment:
      - ENV ASPNETCORE_URLS="http://*:5000"
      - ENV ASPNETCORE_ENVIRONMENT="Staging"

    ports:
      - "8080:5000"

    networks:
      - app-internal

networks:
  app-internal:
    driver: bridge