version: '2'

services:

  web:
    container_name: 'coredatastore'
    image: "stuartshay/coredatastore:stable"
    volumes:
      - .:/var/www/aspnetcoreapp
    ports:
     - "5000:5000"
    depends_on:
     - "database"
    networks:
      - aspnetcoreapp-network

  database:
    container_name: 'database'
    image: "stuartshay/coredatastore-postgres:stable"
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - aspnetcoreapp-network


networks:
  aspnetcoreapp-network:
    driver: bridge










