version: '2'

services:
  database:
    image: postgres    
    environment:
      - POSTGRES_USER=nyclandmarks
      - POSTGRES_PASSWORD=nyclandmarks
      - POSTGRES_DB=nyclandmarks
    networks:
      - back-tier
   #ports:
   #   - "5432:5432" 

  api:
    image: stuartshay/coredatastore:api
    links:
      - database  
    environment:
      - ASPNETCORE_URLS=http://api:80
      - ASPNETCORE_ENVIRONMENT=Staging    
    networks:
      - back-tier
    
  frontend:
    image: stuartshay/coredatastore:ui
    links:
      - api
    ports:
      - "80:80"    
    networks:
      - back-tier     

networks:
  back-tier:
    driver: bridge