version: '2'

services:
  # database:
  #   image: postgres    
  #   environment:
  #     - POSTGRES_USER="coredatastore"
  #     - POSTGRES_PASSWORD="123456"
  #   networks:
  #     - back-tier

  api:
    image: stuartshay/coredatastore:api
    # links:
    #   - database  
    environment:
      - ASPNETCORE_URLS=http://api:80
      - ASPNETCORE_ENVIRONMENT=Development    
    networks:
      - back-tier
    
  frontend:
    image: stuartshay/coredatastore:ui
    links:
      - api
    ports:
      - "80:80"    
    networks:
      - back-tier     

networks:
  back-tier:
    driver: bridge