version: '2'

services:

 webapp1:
    container_name: aspnetcore-1
    build:
      context: .
      dockerfile: aspnetcore.dockerfile
    ports:
      - "5000:5000"
    networks:
      - front

 nginx:
    container_name: nginx-1
    build:
      context: .
      dockerfile: nginx.dockerfile
    depends_on:
     - webapp1
    ports:
     - "80:80"
    networks:
    - front

networks:
  front:

