version: '2'

services:
  # database:
  #   image: postgres    
  #   environment:
  #     - POSTGRES_USER="coredatastore"
  #     - POSTGRES_PASSWORD="123456"
  #   networks:
  #     - back-tier

  api:
    image: stuartshay/coredatastore:api
    # links:
    #   - database  
    environment:
      - ENV ASPNETCORE_URLS="http://*:80"
      - ENV ASPNETCORE_ENVIRONMENT="Staging"
    networks:
      - back-tier
    
  frontend:
    image: stuartshay/coredatastore:ui
    links:
      - api
    ports:
      - "80:80"    
    networks:
      - back-tier     

networks:
  back-tier:
    driver: bridge