version: '2'

services:
  database:
    image: postgres    
    environment:
      - POSTGRES_USER="coredatastore"
      - POSTGRES_PASSWORD="123456"
    networks:
      - back-tier

  api:
    image: stuartshay/coredatastore:api
    links:
      - database  
    environment:
      - ENV ASPNETCORE_URLS="http://*:5000"
      - ENV ASPNETCORE_ENVIRONMENT="Staging"    
    ports:
      - "80:5000"     
    networks:
      - back-tier
    
  frontend:
    image: stuartshay/coredatastore:ui
    links:
      - api
    ports:
      - "8080:80"    
    networks:
      - back-tier     

networks:
  back-tier:
    driver: bridge